build:
  verbosity: detailed

image: Visual Studio 2019

install:
  - ps: Install-Product node 8 x64
  - ps: dotnet tool restore

build_script:
  - cmd: dotnet fake build -t Build

cache:
- "%LOCALAPPDATA%\\Yarn"
